CREATE TABLE `trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`direction` enum('long','short') NOT NULL,
	`status` enum('open','closed','cancelled') NOT NULL DEFAULT 'open',
	`entryPrice` decimal(18,8) NOT NULL,
	`exitPrice` decimal(18,8),
	`stopLoss` decimal(18,8),
	`takeProfit` decimal(18,8),
	`positionSize` decimal(18,8),
	`riskReward` decimal(8,2),
	`riskPercent` decimal(8,2),
	`pnlPips` decimal(12,2),
	`pnlAmount` decimal(18,2),
	`timeframe` varchar(10),
	`followedStrategy` boolean,
	`setupType` varchar(64),
	`notes` text,
	`deviations` text,
	`improvements` text,
	`entryTime` timestamp NOT NULL,
	`exitTime` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trades_id` PRIMARY KEY(`id`)
);
